---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mdepietro.
--- DateTime: 23/03/2020 19:49
---

local PietroEngine = Object:extend()

function PietroEngine:load()
    loadFolder('lib/engine')
    loadFolder('lib/shapes')
    loadFolder('lib/areas')
    loadFolder('lib/objects')
    loadFolder('lib/rooms')
end

function loadFolder(path)
    local files = {}
    recursiveEnumerate(path, files)
    requireFiles(files)
end

return PietroEngine