---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mdepietro.
--- DateTime: 05/04/2020 17:43
---

Panel = GameObject:extend()

function Panel:new(area, x, y, opts)
    Panel.super.new(self, area, x, y, opts)
end

function Panel:update(dt)
    Panel.super.update(self, dt)
end

function Panel:draw()
    love.graphics.rectangle('fill', self.x, self.y, self.width or 50, self.height or 50)
end