---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mdepietro.
--- DateTime: 05/04/2020 16:48
---

Player = GameObject:extend()

function Player:new(area, x, y, opts)
    Player.super.new(self, area, x, y, opts)
    self.acceleration = 1.1
    self.accPower = 0.01
    self.maxSpeed = 1.5
    self.actions = {}
end

function Player:update(dt)
    Player.super.update(self, dt)
    for _, action in pairs(self.actions) do
        action()
    end
end

function Player:draw()
    love.graphics.setColor({ 100, 100, 50, 1 })
    love.graphics.print(
            self.speed * 100,
            0,
            0
    )
    love.graphics.setColor(100, 100, 50)
    love.graphics.rectangle('fill', self.x, self.y, self.width or 50, self.height or 50)
end
