---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mdepietro.
--- DateTime: 25/03/2020 19:34
---

FilterRules = {}

function FilterRules:isEnemy(object)
    if object:is(Enemy) then
        return true
    end
end

function FilterRules:isHealthy(object)
    if object.hp and object.hp >= 50 then
        return true
    end
end