---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mdepietro.
--- DateTime: 04/04/2020 21:32
---

Motion = Object:extend()
local sqrt2 = math.sqrt(2)

function Motion:calculateDiagonal(dx, dy)
    if dx ~= 0.0 and dy ~= 0.0 then
        -- Diagonal movement (as in 45°)
        dx, dy = dx / sqrt2, dy / sqrt2
    end
    return dx, dy
end

function Motion:calculateMotion(dx, dy, speed)
    return dx * speed, dy * speed
end

function Motion:move(x, y, dx, dy, dt)
    return x + dx * dt, y + dy * dt
end

function Motion:calculateSpeed(x, y, dx, dy)
    return math.dist(x, y, dx, dy)
end