---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mdepietro.
--- DateTime: 04/04/2020 21:30
---

PietroEngine = Object:extend()

function PietroEngine:load()
    Area = require 'lib.engine.Area'
    GameObject = require 'lib.engine.GameObject'
end