---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mdepietro.
--- DateTime: 05/04/2020 16:47
---

Room = Object:extend()

function Room:new()
    self.area = Area()
    self.area:addGameObject('Player',10,100, {radius = 200})
    Controller:new(self.area.game_objects[1])
end