---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mdepietro.
--- DateTime: 15/01/2020 20:57
---

local Test = Class:extend()

function Test:new()

end

function Test:update(dt)

end

function Test:draw()

end

return Test