---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mdepietro.
--- DateTime: 20/03/2020 18:36
---

Object = require 'vendor/classic/classic'

AInitRoom = Room:extend()

function AInitRoom:new()
    AInitRoom.super:new()
  --  self.area:addGameObject('GameCircle', 200, 200, { width = 200 })
end

function AInitRoom:update(dt)
    self.area:update(dt)
end

function AInitRoom:draw()
    self.area:draw()
end